#ifndef __MT6701_H__
#define __MT6701_H__		

///////////////////////////加入项目的关联头文件////////////////////////////////////

#include "main.h"

#include "spi.h"

#define _2PI 6.28318530718


#define STM32_SPI_PORT		hspi1 	// I2C port as defined in main generated by CubeMx

#define abs(x) ((x)>0?(x):-(x))

//引脚定义
#define GPIO_TYPE    GPIOC
#define MT6701_CSN          4       //片选CSN引脚        PA6
// #define MT6701_CS_GPIO_Port   GPIOA
// #define	 MT6701_CS_Pin   6

#define MT6701_CSN_SET     GPIO_TYPE->BSRR = (1U << MT6701_CSN)          // 置高
#define MT6701_CSN_CLR     GPIO_TYPE->BSRR = (1U << (MT6701_CSN + 16))   // 置低

#define MT6701_CS_Enable() 	HAL_GPIO_WritePin(MT6701_CS_GPIO_Port, MT6701_CS_Pin, GPIO_PIN_RESET)
#define MT6701_CS_Disable() 	HAL_GPIO_WritePin(MT6701_CS_GPIO_Port, MT6701_CS_Pin, GPIO_PIN_SET)



//void MT6701_Read_RAW(uint8_t* pBuffer);
//float MT6701_GetRawAngle(void);
float angleRead( void );
//angle_raw返回原始角度数据，angle转换后的角度值：0-360,field_status磁场强度；
void mt6701_read(uint16_t*angle_raw, float*angle, uint8_t*field_status);
float GetAngle(float rawAngle);
#endif

